// Generated by gencpp from file tutorial/my_message.msg
// DO NOT EDIT!


#ifndef TUTORIAL_MESSAGE_MY_MESSAGE_H
#define TUTORIAL_MESSAGE_MY_MESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace tutorial
{
template <class ContainerAllocator>
struct my_message_
{
  typedef my_message_<ContainerAllocator> Type;

  my_message_()
    : temp(0.0)
    , pressure(0.0)  {
    }
  my_message_(const ContainerAllocator& _alloc)
    : temp(0.0)
    , pressure(0.0)  {
  (void)_alloc;
    }



   typedef double _temp_type;
  _temp_type temp;

   typedef double _pressure_type;
  _pressure_type pressure;





  typedef boost::shared_ptr< ::tutorial::my_message_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::tutorial::my_message_<ContainerAllocator> const> ConstPtr;

}; // struct my_message_

typedef ::tutorial::my_message_<std::allocator<void> > my_message;

typedef boost::shared_ptr< ::tutorial::my_message > my_messagePtr;
typedef boost::shared_ptr< ::tutorial::my_message const> my_messageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::tutorial::my_message_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::tutorial::my_message_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::tutorial::my_message_<ContainerAllocator1> & lhs, const ::tutorial::my_message_<ContainerAllocator2> & rhs)
{
  return lhs.temp == rhs.temp &&
    lhs.pressure == rhs.pressure;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::tutorial::my_message_<ContainerAllocator1> & lhs, const ::tutorial::my_message_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::tutorial::my_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::tutorial::my_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial::my_message_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::tutorial::my_message_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial::my_message_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::tutorial::my_message_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::tutorial::my_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66c861d7d072cf2ed79d84c9e166648a";
  }

  static const char* value(const ::tutorial::my_message_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66c861d7d072cf2eULL;
  static const uint64_t static_value2 = 0xd79d84c9e166648aULL;
};

template<class ContainerAllocator>
struct DataType< ::tutorial::my_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tutorial/my_message";
  }

  static const char* value(const ::tutorial::my_message_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::tutorial::my_message_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 temp\n"
"float64 pressure\n"
;
  }

  static const char* value(const ::tutorial::my_message_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::tutorial::my_message_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.temp);
      stream.next(m.pressure);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_message_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::tutorial::my_message_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::tutorial::my_message_<ContainerAllocator>& v)
  {
    s << indent << "temp: ";
    Printer<double>::stream(s, indent + "  ", v.temp);
    s << indent << "pressure: ";
    Printer<double>::stream(s, indent + "  ", v.pressure);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TUTORIAL_MESSAGE_MY_MESSAGE_H
